ALTER TABLE insurances ADD COLUMN IF NOT EXISTS has_copay BOOLEAN DEFAULT false;
ALTER TABLE insurances ADD COLUMN IF NOT EXISTS modality TEXT DEFAULT 'DESCONOCIDO';

ALTER TABLE insurance_treatments ADD COLUMN IF NOT EXISTS coverage_price NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE insurance_treatments ADD COLUMN IF NOT EXISTS copay_price NUMERIC NOT NULL DEFAULT 0;
